# Site settings
title: "BugKrusha"
description: >
  I create.

author: Jon-Tait Beason
email: 
twitter_username: bugkrusha
github_username: bugkrusha

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bugkrusha.com" # the base hostname & protocol for your site

google_analytics_id:
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

